#+TITLE:Some key numbers that every effective altruist should know
#+AUTHOR: Pablo Stafforini <pablo@stafforini.com>

This is a repository for the Anki deck "Some key numbers that every effective altruist should know". See the [[https://forum.effectivealtruism.org/posts/o9SLSkPJ6A2MWb9Bf/anki-deck-for-some-key-numbers-that-almost-every-ea-should][original announcement]] posted to the Effective Altruism Forum for details.

* Downloading for the first time
If you never used the deck before, you can download it straight away from [[https://ankiweb.net/shared/info/1810848608][AnkiWeb]].

* Upgrading to the latest version
If you are already using a version of the deck and would like to upgrade to the latest version, you first need to install the [[https://github.com/Stvad/CrowdAnki][CrowdAnki]] add-on:

1. Open Anki on your computer and select /Tools/ > /Add-ons/ > /Get Add-ons/.
2. Paste the code ~1788670778~ and click /OK/.
3. Restart Anki.

You're now ready to upgrade:

1. Go to the [[https://github.com/benthamite/EA-numbers/releases][Releases]] page.
2. Under /Assets/, download the file ~EA-numbers.zip~.
3. Extract the contents of the file to your computer.
4. Open Anki and make sure your devices are all synchronized.
5. Select /File/ > /CrowdAnki: Import from disk/.
6. Browse for and select the folder you extracted, named ~EA-numbers~.
7. Don't change anything in the CrowdAnki Import Settings dialog box that opens—just press OK to start the import. A dialog box should then confirm that the import was successful.

* Building the deck from the source file
The deck is created by pushing the contents of an org mode file to the Anki desktop app (with the [[https://github.com/louietan/anki-editor][anki-editor Emacs package]]); exporting the generated deck to a JSON file (with the [[https://github.com/Stvad/CrowdAnki][CrowdAnki Anki add-on]]); and uploading this file to the current repository. If you are an Emacs user, you can simplify the process by creating the deck directly from the [[https://github.com/benthamite/EA-numbers/blob/main/source.org][source file]]. (Please note that you need to delete the lines starting with ~:ANKI_NOTE_ID:~ under each main heading; otherwise anki-editor will emit an error message.)

In case it is of interest, here is my anki-editor configuration (assumes you have [[https://github.com/raxod502/straight.el][straight]], [[https://github.com/jwiegley/use-package][use-package]] and [[https://github.com/noctuid/general.el][general]] installed):

#+begin_src emacs-lisp :results silent
(use-package anki-editor
  :straight (:fork (:repo "leoc/anki-editor" :branch "develop"))
  :init
  (setq-default anki-editor-use-math-jax t) ; github.com/louietan/anki-editor/issues/60#issuecomment-617441799
  ;; create custom key map
  (progn
    (defvar anki-editor-mode-map (make-sparse-keymap))
    (add-to-list 'minor-mode-map-alist (cons 'anki-editor-mode
                                             anki-editor-mode-map)))
  :custom
  (anki-editor-create-decks t)
  (anki-editor-org-tags-as-anki-tags t)
  :config
  ;; The very simple Keyboard Maestro macro called by this function may be downloaded here:
  ;; https://www.dropbox.com/s/or5h9v9ydnd3z9f/Anki%3A%20open%20note%20ID.kmmacros?dl=0
  (defun ps/anki-editor-open-note-externally ()
    "Copy note id to clipboard, switch to Anki desktop, and open note in browser."
    (interactive)
    (let ((note-id (org-entry-get nil "ANKI_NOTE_ID")))
      (if (eq note-id nil)
          (error "Note id not found")
        (progn
          (kill-new (concat "nid:" note-id))
          (shell-command "osascript -e 'tell application \"Keyboard Maestro Engine\" to do script \"496A3425-8985-4117-AE0F-ABD6DC85FB9F\"'")))))
  :general
  ("M-A-i" 'anki-editor-mode)
  (anki-editor-mode-map
   "s-c" 'anki-editor-cloze-region
   "s-i" 'anki-editor-insert-note
   "s-n" 'anki-editor-push-new-notes
   "s-x" 'ps/anki-editor-open-note-externally
   "s-a" 'anki-editor-push-notes ; push all notes
   "s-h" (lambda () (interactive) (anki-editor-push-notes '(4))))) ; push notes under heading
#+end_src

* Browsing the deck without using Anki
If you would like to browse the deck's contents without using Anki, just go to the [[https://github.com/benthamite/EA-numbers/blob/main/source.org][source file]].

You can also study the deck using [[https://app.thoughtsaver.com/embed/cBGzVcb6Lx7X][Thought Saver]], an application developed by Spencer Greenberg. You can find the deck [[https://app.thoughtsaver.com/embed/cBGzVcb6Lx7X][here]] (you'll need to create an account to access it).

* Staying abreast of new releases
If you would like to be notified when a new version of the deck is released, click on /Watch/ in the top right corner, select /Custom/ and tick the /Releases/ box.

* Bug reports and improvement suggestions
If you would like to report an error or inaccuracy with the deck, or would like to suggest questions or topics for future releases, please [[https://github.com/benthamite/EA-numbers/issues][open an issue]].
