* Downloading for the first time
If you never used the deck before, you can download it straight away from [[https://ankiweb.net/shared/info/1810848608][AnkiWeb]].

* Upgrading to the latest version
If you are already using a version of the deck and would like to upgrade to the latest version, you first need to install the [[https://github.com/Stvad/CrowdAnki][CrowdAnki]] add-on:

1. Open Anki on your computer and select /Tools/ > /Add-ons/ > /Get Add-ons/.
2. Paste the code ~1788670778~ and click /OK/.
3. Restart Anki.

You're now ready to upgrade:

1. Go to the [[https://github.com/benthamite/EA-numbers/releases][Releases]] page.
2. Under /Assets/, download the file ~EA-numbers.zip~.
3. Extract the contents of the file to your computer.
4. Open Anki and make sure your devices are all synchronized.
5. Select /File/ > /CrowdAnki: Import from disk/.
6. Browse for and select the folder you extracted, named ~EA-numbers~.
7. Don't change anything in the CrowdAnki Import Settings dialog box that opens—just press OK to start the import. A dialog box should then confirm that the import was successful.

* Building the deck from the source file
The deck is created by pushing the contents of an org mode file to the Anki desktop app (with the [[https://github.com/louietan/anki-editor][anki-editor Emacs package]]); exporting the generated deck to a JSON file (with the [[https://github.com/Stvad/CrowdAnki][CrowdAnki Anki add-on]]); and uploading this file to the current repository. If you are an Emacs user, you can simplify the process by creating the deck directly from the [[https://github.com/benthamite/EA-numbers/blob/main/source.org][source file]]. (Please note that you need to delete the lines starting with ~:ANKI_NOTE_ID:~ under each main heading; otherwise anki-editor will emit an error message.)

In case it is of interest, here is my anki-editor configuration:

#+begin_src emacs-lisp :results silent
(use-package anki-editor
  :after org
  :custom
  (anki-editor-create-decks t)
  (anki-editor-org-tags-as-anki-tags t)
  :init
  ;; github.com/louietan/anki-editor/issues/60#issuecomment-617441799
  (setq-default anki-editor-use-math-jax t)
  ;; create custom key map
  (progn
    (defvar anki-editor-mode-map (make-sparse-keymap))
    (add-to-list 'minor-mode-map-alist (cons 'anki-editor-mode
					     anki-editor-mode-map)))
  :config
  ;; github.com/louietan/anki-editor/issues/39#issuecomment-606156415
  (defun filter-out-p (str _ _)
    (replace-regexp-in-string "\n<p>\\|</p>\n\\|<p>\\|</p>" "" str))
  (setq anki-editor--ox-anki-html-backend
	(org-export-create-backend
	 :parent 'html
	 :filters
	 '((:filter-paragraph . filter-out-p))))
;; requires github.com/noctuid/general.el; otherwise use `:bind' and adjust the syntax
  :general
  ("A-i" 'anki-editor-mode)
  (anki-editor-mode-map
   "s-c" 'anki-editor-cloze-region
   "s-i" 'anki-editor-insert-note
   "s-p" 'anki-editor-push-notes))
#+end_src

* Browsing the deck without using Anki
If you would like to browse the deck's contents without using Anki, just go to the [[https://github.com/benthamite/EA-numbers/blob/main/source.org][source file]].

* Staying abreast of new releases
If you would like to be notified when a new version of the deck is released, click on /Watch/ in the top right corner, select /Custom/ and tick the /Releases/ box.

* Bug reports and improvement suggestions
If you would like to report an error or inaccuracy with the deck, or would like to suggest questions or topics for future releases, please [[https://github.com/benthamite/EA-numbers/issues][open an issue]].
