#+TITLE:Some key numbers that every effective altruist should know
#+AUTHOR: Pablo Stafforini <pablo@stafforini.com>

This is a repository for the Anki deck "Some key numbers that every effective altruist should know". See the [[https://forum.effectivealtruism.org/posts/o9SLSkPJ6A2MWb9Bf/anki-deck-for-some-key-numbers-that-almost-every-ea-should][original announcement]] posted to the Effective Altruism Forum for details.

* Downloading for the first time
If you never used the deck before, you can download it straight away from [[https://ankiweb.net/shared/info/1810848608][AnkiWeb]].

* Upgrading to the latest version
If you are already using a version of the deck and would like to upgrade to the latest version, you first need to install the [[https://github.com/Stvad/CrowdAnki][CrowdAnki]] add-on:

1. Open Anki on your computer and select /Tools/ > /Add-ons/ > /Get Add-ons/.
2. Paste the code ~1788670778~ and click /OK/.
3. Restart Anki.

You're now ready to upgrade. Simply open Anki on your computer, select /File > CrowdAnki: Import git repository/, and enter ~https://github.com/benthamite/EA-numbers~.

* Staying abreast of new releases
If you would like to be notified when a new version of the deck is released, click on /Watch/ in the top right corner, select /Custom/ and tick the /Releases/ box.

* Collaborating
If you would like to fix a mistake or inaccuracy, or add more notes to the deck, you are welcome to do so by following the steps described [[https://github.com/Stvad/CrowdAnki#how-to-collaborate-via-github][here]] (see "How to collaborate via GitHub").

* Etc.
If you still have questions, please [[https://github.com/benthamite/EA-numbers/issues][open an issue]] or [[https://stafforini.com/contact][contact me]].
