#+TITLE: Some key numbers that (almost) every EA should know
#+AUTHOR: Pablo Stafforini <pablo@stafforini.com>

* Age of the universe
  :PROPERTIES:
  :ANKI_DECK: EA-numbers
  :ANKI_NOTE_TYPE: EA
  :ANKI_TAGS: ea_numbers
  :ANKI_NOTE_ID: 1624919221164
  :END:
** Front
What is the age of the universe?
** Back
13.772 billion years.
** Source
"In physical cosmology, the age of the universe is the time elapsed since the Big Bang. Today, astronomers have derived two different measurements of the age of the universe: a measurement based on direct observations of an early state of the universe, which indicate an age of 13.772 ± 0.040 billion years within the Lambda-CDM concordance model as of 2018; and a measurement based on the observations of the local, modern universe which suggest a younger age." ([[https://en.wikipedia.org/wiki/Age_of_the_universe][Wikipedia]])
* Age of Earth
  :PROPERTIES:
  :ANKI_DECK: EA-numbers
  :ANKI_NOTE_TYPE: EA
  :ANKI_TAGS: ea_numbers
  :ANKI_NOTE_ID: 1624919187570
  :END:
** Front
What is the age of Earth?
** Back
4.54 billion years.
** Source
"The age of Earth is estimated to be 4.54 ± 0.05 billion years (4.54 × 109 years ± 1%). This age may represent the age of the Earth's accretion, or core formation, or of the material from which the Earth formed. This dating is based on evidence from radiometric age-dating of meteorite material and is consistent with the radiometric ages of the oldest-known terrestrial and lunar samples." ([[https://en.wikipedia.org/wiki/Age_of_Earth][Wikipedia]])
* Age of /homo sapiens/
  :PROPERTIES:
  :ANKI_DECK: EA-numbers
  :ANKI_NOTE_TYPE: EA
  :ANKI_TAGS: ea_numbers
  :ANKI_NOTE_ID: 1624919187722
  :END:
** Front
What is the age of /homo sapiens/?
** Back
300,000 years.
** Source
"H. sapiens emerged around 300,000 years ago, evolving from Homo erectus and migrating out of Africa, gradually replacing local populations of archaic humans." ([[https://en.wikipedia.org/wiki/Human][Wikipedia]])
* Humans who ever lived
  :PROPERTIES:
  :ANKI_DECK: EA-numbers
  :ANKI_NOTE_TYPE: EA
  :ANKI_TAGS: ea_numbers
  :ANKI_NOTE_ID: 1624919187818
  :END:
** Front
How many humans have ever lived?
** Back
Around 108 billion.

** Source
[[https://web.archive.org/web/20120308152306/https://www.prb.org/Articles/2002/HowManyPeopleHaveEverLivedonEarth.aspx][Population Reference Bureau]].
* Invention of writing
  :PROPERTIES:
  :ANKI_DECK: EA-numbers
  :ANKI_NOTE_TYPE: EA
  :ANKI_TAGS: ea_numbers
  :ANKI_NOTE_ID: 1624919187907
  :END:
** Front
When was writing invented?
** Back
Between 3400 and 3250 BCE.

** Source
"the discovery of the scripts of ancient Mesoamerica, far away from Middle Eastern sources, proved that writing had been invented more than once. Scholars now recognize that writing may have independently developed in at least four ancient civilizations: Mesopotamia (between 3400 and 3100 BCE), Egypt (around 3250 BCE), China (1200 BCE), and lowland areas of Southern Mexico and Guatemala (by 500 BCE)." ([[https://en.wikipedia.org/wiki/History_of_writing#Inventions_of_writing][Wikipedia]])
* Neolithic revolution
  :PROPERTIES:
  :ANKI_DECK: EA-numbers
  :ANKI_NOTE_TYPE: EA
  :ANKI_TAGS: ea_numbers
  :ANKI_NOTE_ID: 1624919188219
  :END:
** Front
When did the neolithic revolution occur?
** Back
Around 10,000 BCE.
** Source
"Archaeological data indicates that the domestication of various types of plants and animals happened in separate locations worldwide, starting in the geological epoch of the Holocene 11,700 years ago. It was the world's first historically verifiable revolution in agriculture." ([[https://en.wikipedia.org/wiki/Neolithic_Revolution][Wikipedia]])
* Industrial revolution
  :PROPERTIES:
  :ANKI_DECK: EA-numbers
  :ANKI_NOTE_TYPE: EA
  :ANKI_TAGS: ea_numbers
  :ANKI_NOTE_ID: 1624919188322
  :END:
** Front
When did the industrial revolution occur?
** Back
Between 1760 and 1840.
** Source
"The Industrial Revolution was the transition to new manufacturing processes in Europe and the United States, in the period from between 1760 to 1820 and 1840." ([[https://en.wikipedia.org/wiki/Industrial_Revolution][Wikipedia]])
* World median annual income
  :PROPERTIES:
  :ANKI_DECK: EA-numbers
  :ANKI_NOTE_TYPE: EA
  :ANKI_TAGS: ea_numbers
  :ANKI_NOTE_ID: 1624919188442
  :END:
** Front
What is median annual income, globally?
** Back
Int$2,835 (2019).
** Source
[[https://drive.google.com/file/d/17_XiLHc6g8FRPa5ukiU-YjGByHbCV_Jr/view][Data for Giving What We Can's 'How rich are you?' calculator]] (cell L128). You can get a vivid sense of what it's like to live with this income by visiting [[https://www.gapminder.org/dollar-street?min=230&max=240&p=][Dollar Street]] ($2835/year corresponds to $236.25/month).
* Gross world product
  :PROPERTIES:
  :ANKI_DECK: EA-numbers
  :ANKI_NOTE_TYPE: EA
  :ANKI_TAGS: ea_numbers
  :ANKI_NOTE_ID: 1624919188541
  :END:
** Front
What is gross world product?
** Back
87.735 trillion (2019), in current USD.
** Source
[[https://data.worldbank.org/indicator/NY.GDP.MKTP.CD][World Bank]].
* World GDP per capita
  :PROPERTIES:
  :ANKI_DECK: EA-numbers
  :ANKI_NOTE_TYPE: EA
  :ANKI_TAGS: ea_numbers
  :ANKI_NOTE_ID: 1624919188644
  :END:
** Front
What is world GDP per capita (PPP)?
** Back
Int$17,633 (2019).

** Source
[[https://data.worldbank.org/indicator/NY.GDP.PCAP.PP.CD?most_recent_value_desc=true][World Bank]].
* China's GDP per capita
  :PROPERTIES:
  :ANKI_DECK: EA-numbers
  :ANKI_NOTE_TYPE: EA
  :ANKI_TAGS: ea_numbers
  :ANKI_NOTE_ID: 1624919188763
  :END:
** Front
What is China's GDP per capita (PPP)?
** Back
Int$16,804 (2019).

** Source
[[https://data.worldbank.org/indicator/NY.GDP.PCAP.PP.CD?most_recent_value_desc=true][World Bank]].
* United States's GDP per capita
  :PROPERTIES:
  :ANKI_DECK: EA-numbers
  :ANKI_NOTE_TYPE: EA
  :ANKI_TAGS: ea_numbers
  :ANKI_NOTE_ID: 1624919188841
  :END:
** Front
What is the United States's GDP per capita (PPP)?
** Back
Int$65,298 (2019).

** Source
[[https://data.worldbank.org/indicator/NY.GDP.PCAP.PP.CD?most_recent_value_desc=true][World Bank]].
* India's GDP per capita
  :PROPERTIES:
  :ANKI_DECK: EA-numbers
  :ANKI_NOTE_TYPE: EA
  :ANKI_TAGS: ea_numbers
  :ANKI_NOTE_ID: 1624919188917
  :END:
** Front
What is India's GDP per capita (PPP)?
** Back
Int$6,997 (2019).

** Source
[[https://data.worldbank.org/indicator/NY.GDP.PCAP.PP.CD?most_recent_value_desc=true][World Bank]].
* European Union's GDP per capita
  :PROPERTIES:
  :ANKI_DECK: EA-numbers
  :ANKI_NOTE_TYPE: EA
  :ANKI_TAGS: ea_numbers
  :ANKI_NOTE_ID: 1624919188982
  :END:
** Front
What is the European Union's GDP per capita (PPP)?
** Back
Int$46,443 (2019).

** Source
[[https://data.worldbank.org/indicator/NY.GDP.PCAP.PP.CD?most_recent_value_desc=true][World Bank]].
* Poorest Americans and richest Indians
  :PROPERTIES:
  :ANKI_DECK: EA-numbers
  :ANKI_NOTE_TYPE: EA
  :ANKI_TAGS: ea_numbers
  :ANKI_NOTE_ID: 1624919189374
  :END:
** Front
For what /n/ is the poorest /n%/ of Americans roughly as rich as the richest /n%/ of Indians?
** Back
5, i.e. the poorest 5% of Americans are roughly as rich as the richest 5% of Indians.

** Source
[[http://www.marbiru.com/inequality/][Uri Bram]], based on data from Branko Milanović.
* Fraction of world in extreme poverty in 1820
  :PROPERTIES:
  :ANKI_DECK: EA-numbers
  :ANKI_NOTE_TYPE: EA
  :ANKI_TAGS: ea_numbers
  :ANKI_NOTE_ID: 1624919189487
  :END:
** Front
What fraction of the world's population in 1820 lived in extreme poverty?
** Back
About 90%.
** Source
[[https://ourworldindata.org/grapher/world-population-in-extreme-poverty-absolute?country=~OWID_WRL][Our World in Data]]. 'Extreme poverty' is defined as living with less than Int$1.90 per day.
* Fraction of world currently in extreme poverty
  :PROPERTIES:
  :ANKI_DECK: EA-numbers
  :ANKI_NOTE_TYPE: EA
  :ANKI_TAGS: ea_numbers
  :ANKI_NOTE_ID: 1624919189564
  :END:
** Front
What fraction of the world's population lives in extreme poverty?
** Back
About 10% (2015).
** Source
[[https://ourworldindata.org/grapher/world-population-in-extreme-poverty-absolute?country=~OWID_WRL][Our World in Data]]. 'Extreme poverty' is defined as living with less than Int$1.90 per day.
* Time until Earth no longer habitable
  :PROPERTIES:
  :ANKI_DECK: EA-numbers
  :ANKI_NOTE_TYPE: EA
  :ANKI_TAGS: ea_numbers
  :ANKI_NOTE_ID: 1624919190658
  :END:
** Front
For how long will Earth remain habitable, absent big intervention?
** Back
Between 800 million and two billion years.

** Source
"We can be reasonably confident that the runaway and moist greenhouse effects [...] pose an upper bound on how long life can continue to exist on Earth, but we remain uncertain about when they will occur, due to the familiar limitations of our climate models. Wolf & Toon (2015) find a moist greenhouse will occur at around 2 billion years, whereas Leconte et al. (2013) place a lower bound at 1 billion years.

"The open question is whether carbon dioxide depletion or temperature increases will render Earth uninhabitable before the runaway or moist greenhouse limits are reached. Rushby et al. (2018) estimate carbon dioxide depletion will occur in around 800 million years for C3 photosynthesis, and around 500 million years later for C4 photosynthesis.

"Over such long timespans, we cannot ignore the possibility that evolution may lead to new life forms able to exist in climates inhospitable to presently existing life forms. Indeed, the first C4 plants appeared around 32 million
years ago (Kellog, 2013)." ([[https://theprecipice.com/][Ord 2020]]: 296–297)
* Number of working days in a year
  :PROPERTIES:
  :ANKI_DECK: EA-numbers
  :ANKI_NOTE_TYPE: EA
  :ANKI_TAGS: ea_numbers
  :ANKI_NOTE_ID: 1624919190732
  :END:
** Front
What is the number of working days in a year?
** Back
Around 250.
** Source
According to [[https://www.work-day.co.uk/][this online calculator]], the figures for the US, UK and Germany are 250, 253 and 255, respectively.
* Number of working hours in a year
  :PROPERTIES:
  :ANKI_DECK: EA-numbers
  :ANKI_NOTE_TYPE: EA
  :ANKI_TAGS: ea_numbers
  :ANKI_NOTE_ID: 1624919190837
  :END:
** Front
What is the number of working hours in a year?
** Back
For Western nations, between 1,350 (Germany) and 1,750 (US).

** Source
[[https://ourworldindata.org/working-hours][Our World in Data]].
* Good Ventures's total assets
  :PROPERTIES:
  :ANKI_DECK: EA-numbers
  :ANKI_NOTE_TYPE: EA
  :ANKI_TAGS: ea_numbers
  :ANKI_NOTE_ID: 1624919190948
  :END:
** Front
What are Good Ventures's total assets?
** Back
2.114 billion.
** Source
[[https://projects.propublica.org/nonprofits/display_990/461008520/10_2020_prefixes_45-46%2F461008520_201906_990PR_2020102217399905][IRS filling]], p. 2, box 16c.
* World population
  :PROPERTIES:
  :ANKI_DECK: EA-numbers
  :ANKI_NOTE_TYPE: EA
  :ANKI_TAGS: ea_numbers
  :ANKI_NOTE_ID: 1624919191065
  :END:
** Front
What is the world population?
** Back
7.87 billion (2021).
** Source
[[https://ourworldindata.org/grapher/projected-population-by-country?country=~OWID_WRL][Our World in Data]].
* Projected world population for 2050
  :PROPERTIES:
  :ANKI_DECK: EA-numbers
  :ANKI_NOTE_TYPE: EA
  :ANKI_TAGS: ea_numbers
  :ANKI_NOTE_ID: 1624919191370
  :END:
** Front
What is the projected world population for 2050?
** Back
9.74 billion.
** Source
[[https://ourworldindata.org/grapher/projected-population-by-country?country=~OWID_WRL][Our World in Data]].
* Peak world population
  :PROPERTIES:
  :ANKI_DECK: EA-numbers
  :ANKI_NOTE_TYPE: EA
  :ANKI_TAGS: ea_numbers
  :ANKI_NOTE_ID: 1624919191471
  :END:
** Front
At what number will world population peak?
** Back
Around 11 billion.
** Source
"In this projection the world population will be around 10.88 billion in 2100 and we would therefore expect ‘peak population’ to occur early in the 22nd century, at not much more than 10.88 billion." ([[https://ourworldindata.org/future-population-growth#the-un-population-projection-by-country-and-world-region-until-2100][Our World in Data]])
* Population of China
  :PROPERTIES:
  :ANKI_DECK: EA-numbers
  :ANKI_NOTE_TYPE: EA
  :ANKI_TAGS: ea_numbers
  :ANKI_NOTE_ID: 1624919191562
  :END:
** Front
What is the population of China?
** Back
1.44 billion (2021).
** Source
[[https://ourworldindata.org/grapher/projected-population-by-country?country=~CHN][Our World in Data]].
* Population of China in 2050
  :PROPERTIES:
  :ANKI_DECK: EA-numbers
  :ANKI_NOTE_TYPE: EA
  :ANKI_TAGS: ea_numbers
  :ANKI_NOTE_ID: 1624919191641
  :END:
** Front
What is the population of China projected for 2050?
** Back
1.40 billion.
** Source
[[https://ourworldindata.org/grapher/projected-population-by-country?country=~CHN][Our World in Data]].
* Population of India
  :PROPERTIES:
  :ANKI_DECK: EA-numbers
  :ANKI_NOTE_TYPE: EA
  :ANKI_TAGS: ea_numbers
  :ANKI_NOTE_ID: 1624919191721
  :END:
** Front
What is the population of India?
** Back
1.39 billion (2021).
** Source
[[https://ourworldindata.org/grapher/projected-population-by-country?country=~IND][Our World in Data]].
* Population of India in 2050
  :PROPERTIES:
  :ANKI_DECK: EA-numbers
  :ANKI_NOTE_TYPE: EA
  :ANKI_TAGS: ea_numbers
  :ANKI_NOTE_ID: 1624919191820
  :END:
** Front
What is the population of India projected for 2050?
** Back
1.64 billion.
** Source
[[https://ourworldindata.org/grapher/projected-population-by-country?country=~IND][Our World in Data]].
* Population of US
  :PROPERTIES:
  :ANKI_DECK: EA-numbers
  :ANKI_NOTE_TYPE: EA
  :ANKI_TAGS: ea_numbers
  :ANKI_NOTE_ID: 1624919191944
  :END:
** Front
What is the population of the United States?
** Back
333 million (2021).
** Source
[[https://ourworldindata.org/grapher/projected-population-by-country?country=~USA][Our World in Data]].
* Population of US in 2050
  :PROPERTIES:
  :ANKI_DECK: EA-numbers
  :ANKI_NOTE_TYPE: EA
  :ANKI_TAGS: ea_numbers
  :ANKI_NOTE_ID: 1624919192014
  :END:
** Front
What is the population of the United States projected for 2050?
** Back
379 million.
** Source
[[https://ourworldindata.org/grapher/projected-population-by-country?country=~USA][Our World in Data]].
* Population of Europe
  :PROPERTIES:
  :ANKI_DECK: EA-numbers
  :ANKI_NOTE_TYPE: EA
  :ANKI_TAGS: ea_numbers
  :ANKI_NOTE_ID: 1624919192098
  :END:
** Front
What is the population of Europe?
** Back
748 million (2021).
** Source
[[https://ourworldindata.org/grapher/projected-population-by-country?country=~Europe][Our World in Data]].
* Population of Europe in 2050
  :PROPERTIES:
  :ANKI_DECK: EA-numbers
  :ANKI_NOTE_TYPE: EA
  :ANKI_TAGS: ea_numbers
  :ANKI_NOTE_ID: 1624919192413
  :END:
** Front
What is the population of Europe projected for 2050?
** Back
710 million.
** Source
[[https://ourworldindata.org/grapher/projected-population-by-country?country=~Europe][Our World in Data]].
* Energy consumed by human brain
  :PROPERTIES:
  :ANKI_DECK: EA-numbers
  :ANKI_NOTE_TYPE: EA
  :ANKI_TAGS: ea_numbers
  :ANKI_NOTE_ID: 1624919192488
  :END:
** Front
How much energy does a human brain consume?
** Back
20 W.
** Source
[[https://hypertextbook.com/facts/2001/JacquelineLing.shtml][The Physics Factbook]].
* Value of statistical life in the US
  :PROPERTIES:
  :ANKI_DECK: EA-numbers
  :ANKI_NOTE_TYPE: EA
  :ANKI_TAGS: ea_numbers
  :ANKI_NOTE_ID: 1624919193546
  :END:
** Front
What are typical estimates for the value of statistical life in the United States?
** Back
Around $10 million.
** Source
"The value of a statistical life (VSL) is the local tradeoff rate between fatality risk and money. When the tradeoff values are derived from choices in market contexts the VSL serves as both a measure of the population’s willingness to pay for risk reduction and the marginal cost of enhancing safety. Given its fundamental economic role, policy analysts have adopted the VSL as the economically correct measure of the benefit individuals receive from enhancements to their health and safety. Estimates of the VSL for the United States are around $10 million ($2017), and estimates for other countries are generally lower given the positive income elasticity of the VSL." ([[https://doi.org/10.1093/acrefore/9780190625979.013.138][Kniesner & Viscusi 2019]])
* Number of neurons in the human brain
  :PROPERTIES:
  :ANKI_DECK: EA-numbers
  :ANKI_NOTE_TYPE: EA
  :ANKI_TAGS: ea_numbers
  :ANKI_NOTE_ID: 1624919193660
  :END:
** Front
How many neurons are in the human brain?
** Back
86 billion.
** Source
[[https://doi.org/10.1002/cne.21974][Azevedo /et al/ 2009]].
* Total number of neurons in all living animals
  :PROPERTIES:
  :ANKI_DECK: EA-numbers
  :ANKI_NOTE_TYPE: EA
  :ANKI_TAGS: ea_numbers
  :ANKI_NOTE_ID: 1624919193750
  :END:
** Front
How many neurons are contained in the brains of all living animals?
** Back
Around \(3 \times 10^{23}\).
** Source
Georgia Ray's [[https://docs.google.com/spreadsheets/d/1MbkEkQy9OfUNfb27z0zCIaCMTELTdaSB1g9Ds-2WKSU/edit#gid=1855091310][estimates]].
* Human share of total neurons
  :PROPERTIES:
  :ANKI_DECK: EA-numbers
  :ANKI_NOTE_TYPE: EA
  :ANKI_TAGS: ea_numbers
  :ANKI_NOTE_ID: 1624919193840
  :END:
** Front
What fraction of all living neurons are human neurons?
** Back
About 0.22%.
** Source
Computed from Georgia Ray's [[https://docs.google.com/spreadsheets/d/1MbkEkQy9OfUNfb27z0zCIaCMTELTdaSB1g9Ds-2WKSU/edit#gid=1855091310][estimates]].
* Mammal share of total neurons
  :PROPERTIES:
  :ANKI_DECK: EA-numbers
  :ANKI_NOTE_TYPE: EA
  :ANKI_TAGS: ea_numbers
  :ANKI_NOTE_ID: 1624919193914
  :END:
** Front
What fraction of all living neurons are mammal neurons?
** Back
About 0.26%.
** Source
Computed from Georgia Ray's [[https://docs.google.com/spreadsheets/d/1MbkEkQy9OfUNfb27z0zCIaCMTELTdaSB1g9Ds-2WKSU/edit#gid=1855091310][estimates]].
* Bird share of total neurons
  :PROPERTIES:
  :ANKI_DECK: EA-numbers
  :ANKI_NOTE_TYPE: EA
  :ANKI_TAGS: ea_numbers
  :ANKI_NOTE_ID: 1624919193979
  :END:
** Front
What fraction of all living neurons are bird neurons?
** Back
About 0.03%.
** Source
Computed from Georgia Ray's [[https://docs.google.com/spreadsheets/d/1MbkEkQy9OfUNfb27z0zCIaCMTELTdaSB1g9Ds-2WKSU/edit#gid=1855091310][estimates]].
* Fish share of total neurons
  :PROPERTIES:
  :ANKI_DECK: EA-numbers
  :ANKI_NOTE_TYPE: EA
  :ANKI_TAGS: ea_numbers
  :ANKI_NOTE_ID: 1624919194293
  :END:
** Front
What fraction of all living neurons are fish neurons?
** Back
About 33%.
** Source
Computed from Georgia Ray's [[https://docs.google.com/spreadsheets/d/1MbkEkQy9OfUNfb27z0zCIaCMTELTdaSB1g9Ds-2WKSU/edit#gid=1855091310][estimates]].
* Invertebrate share of total neurons
  :PROPERTIES:
  :ANKI_DECK: EA-numbers
  :ANKI_NOTE_TYPE: EA
  :ANKI_TAGS: ea_numbers
  :ANKI_NOTE_ID: 1624919194363
  :END:
** Front
What fraction of all living neurons are invertebrate neurons?
** Back
About 66%.
** Source
Computed from Georgia Ray's [[https://docs.google.com/spreadsheets/d/1MbkEkQy9OfUNfb27z0zCIaCMTELTdaSB1g9Ds-2WKSU/edit#gid=1855091310][estimates]].
* Estimated number of lives saved by smallpox eradication
  :PROPERTIES:
  :ANKI_DECK: EA-numbers
  :ANKI_NOTE_TYPE: EA
  :ANKI_TAGS: ea_numbers
  :ANKI_NOTE_ID: 1624919194430
  :END:
** Front
What is the estimated number of lives saved by smallpox eradication?
** Back
Between 150 and 200 million.
** Source
"To date the eradication of smallpox saved millions of lives. It is impossible to know very exactly how many people would have died of smallpox since 1980 if scientists had not developed the vaccine, but reasonable estimates are in the range of around 5 million lives per year, which implies that between 1980 and 2018 around 150 to 200 million lives have been saved." ([[https://ourworldindata.org/smallpox#lives-saved-from-smallpox-eradication][Our World in Data]])
* Number of deaths from mosquito-borne diseases
  :PROPERTIES:
  :ANKI_DECK: EA-numbers
  :ANKI_NOTE_TYPE: EA
  :ANKI_TAGS: ea_numbers
  :ANKI_NOTE_ID: 1624919194513
  :END:
** Front
How many people have been killed by mosquito-borne diseases?
** Back
About 52 billion.
** Source
[[https://en.wikipedia.org/wiki/Special:BookSources?isbn=9780735235793][Winegard 2019]]. This figure has not been vetted and may not be accurate.
* Open Philanthropy's yearly grants
  :PROPERTIES:
  :ANKI_DECK: EA-numbers
  :ANKI_NOTE_TYPE: EA
  :ANKI_TAGS: ea_numbers
  :ANKI_NOTE_ID: 1624919194632
  :END:
** Front
What is the annual volume of Open Philanthropy's grantmaking?
** Back
Around $270 million (2017–2020).
** Source
[[https://www.openphilanthropy.org/giving/grants][Open Philanthropy]]. Between 2017 and 2020, Open Phil granted $312,480,277, $197,047,477, $297,963,147 and $272,128,076, respectively, the average of which is $269,904,744. Prior to 2017, the annual volume of grants was much lower.
* Open Phil grants in global catastrophic risk
  :PROPERTIES:
  :ANKI_DECK: EA-numbers
  :ANKI_NOTE_TYPE: EA
  :ANKI_TAGS: ea_numbers
  :ANKI_NOTE_ID: 1624919194740
  :END:
** Front
What is the cumulative volume of Open Philanthropy's grants related to global catastrophic risks (including AI and biorisk)?
** Back
$284 million (June 2021).
** Source
[[https://www.openphilanthropy.org/giving/grants][Open Philanthropy]] (adding the following categories: Biosecurity and Pandemic Preparedness [93 million], Global Catastrophic Risks [35 million] and Potential Risks from Advanced Artificial Intelligence [157 million]).
* Open Phil grants in global health and development
  :PROPERTIES:
  :ANKI_DECK: EA-numbers
  :ANKI_NOTE_TYPE: EA
  :ANKI_TAGS: ea_numbers
  :ANKI_NOTE_ID: 1624919194841
  :END:
** Front
What is the cumulative volume of Open Philanthropy's grants related to global health and development?
** Back
$491 million (June 2021).
** Source
[[https://www.openphilanthropy.org/giving/grants][Open Philanthropy]].
* Open Phil grants in to farm animal welfare
  :PROPERTIES:
  :ANKI_DECK: EA-numbers
  :ANKI_NOTE_TYPE: EA
  :ANKI_TAGS: ea_numbers
  :ANKI_NOTE_ID: 1624919194949
  :END:
** Front
What is the cumulative volume of Open Philanthropy's grants related to farm animal welfare?
** Back
$141 million (June 2021).
** Source
[[https://www.openphilanthropy.org/giving/grants][Open Philanthropy]].
* Donations moved by GiveWell
  :PROPERTIES:
  :ANKI_DECK: EA-numbers
  :ANKI_NOTE_TYPE: EA
  :ANKI_TAGS: ea_numbers
  :ANKI_NOTE_ID: 1624919195048
  :END:
** Front
How much money has GiveWell moved?
** Back
$674 million (2011–2019).
** Source
[[https://www.givewell.org/about/impact][GiveWell]].
* Donations by Americans
  :PROPERTIES:
  :ANKI_DECK: EA-numbers
  :ANKI_NOTE_TYPE: EA
  :ANKI_TAGS: ea_numbers
  :ANKI_NOTE_ID: 1624919195164
  :END:
** Front
How much money in total do Americans donate annually?
** Back
$450 billion (2019).
** Source
"Americans gave $449.64 billion in 2019. This reflects a 5.1% increase from 2018." ([[https://www.nptrust.org/philanthropic-resources/charitable-giving-statistics/][National Philanthropic Trust]])
* Donations by American foundations
  :PROPERTIES:
  :ANKI_DECK: EA-numbers
  :ANKI_NOTE_TYPE: EA
  :ANKI_TAGS: ea_numbers
  :ANKI_NOTE_ID: 1624919195463
  :END:
** Front
How much money in total do American foundations donate annually?
** Back
$76 billion (2019).
** Source
"Foundation giving in 2019 increased to $75.69 billion—a 2.5% increase from 2018." ([[https://www.nptrust.org/philanthropic-resources/charitable-giving-statistics/][National Philanthropic Trust]])
* Donations moved by ACE
  :PROPERTIES:
  :ANKI_DECK: EA-numbers
  :ANKI_NOTE_TYPE: EA
  :ANKI_TAGS: ea_numbers
  :ANKI_NOTE_ID: 1624919195547
  :END:
** Front
How much money has Animal Charity Evaluators moved?
** Back
$26.4 million (2014–2019).
** Source
[[https://animalcharityevaluators.org/about/impact/giving-metrics/][Animal Charity Evaluators]].
* Number of GWWC pledges
  :PROPERTIES:
  :ANKI_DECK: EA-numbers
  :ANKI_NOTE_TYPE: EA
  :ANKI_TAGS: ea_numbers
  :ANKI_NOTE_ID: 1624919195663
  :END:
** Front
How many people have taken the Giving What We Can pledge?
** Back
7,233 (June 2021).
** Source
[[https://www.givingwhatwecan.org/about-us/members/][Giving What We Can]].
* EA Forum monthly visitors
  :PROPERTIES:
  :ANKI_DECK: EA-numbers
  :ANKI_NOTE_TYPE: EA
  :ANKI_TAGS: ea_numbers
  :ANKI_NOTE_ID: 1624919195737
  :END:
** Front
How many monthly visitors does the EA Forum receive?
** Back
Around 25,000 (2021).

** Source
CEA (private communication).
* Active EA groups
  :PROPERTIES:
  :ANKI_DECK: EA-numbers
  :ANKI_NOTE_TYPE: EA
  :ANKI_TAGS: ea_numbers
  :ANKI_NOTE_ID: 1624919195841
  :END:
** Front
How many EA active groups are there?
** Back
Perhaps 200 (2021).
** Source
[[https://eahub.org/groups/][EA Hub]] lists 244 groups, but some are probably not active.
* Size of median annual EA donation
  :PROPERTIES:
  :ANKI_DECK: EA-numbers
  :ANKI_NOTE_TYPE: EA
  :ANKI_TAGS: ea_numbers
  :ANKI_NOTE_ID: 1624919195920
  :END:
** Front
What fraction of their income does the median EA donate?
** Back
Around 3% (2018).
** Source
"The median percentage of income donated in 2018 was 3.23%." ([[https://forum.effectivealtruism.org/posts/29xPsh2MKkYGCuJhS/ea-survey-2019-series-donation-data][EA Survey]])
* Number of highly engaged EAs
  :PROPERTIES:
  :ANKI_DECK: EA-numbers
  :ANKI_NOTE_TYPE: EA
  :ANKI_TAGS: ea_numbers
  :ANKI_NOTE_ID: 1624919195985
  :END:
** Front
How many highly engaged EAs are there?
** Back
Around 2,300 (2019).
** Source
"we estimate there are around 2315 highly engaged EAs and 6500 (90% CI: 4700-10,000) active EAs in the community overall." ([[https://forum.effectivealtruism.org/posts/zQRHAFKGWcXXicYMo/ea-survey-2019-series-how-many-people-are-there-in-the-ea][EA Survey]])
* Number of people 80k advises per year
  :PROPERTIES:
  :ANKI_DECK: EA-numbers
  :ANKI_NOTE_TYPE: EA
  :ANKI_TAGS: ea_numbers
  :ANKI_NOTE_ID: 1624919196088
  :END:
** Front
How many people does 80,000 Hours advise in a year?
** Back
Around 240 (average of 2017–2020).
** Source
[[https://docs.google.com/document/d/1rWfQ3Lja2kYoUm_t9uNqBgEn5nz6KL8fmNP5db8cZRU/edit#bookmark=kix.z9l7j1qxtsho][80,000 Hours]].
* Number of bacteria
  :PROPERTIES:
  :ANKI_DECK: EA-numbers
  :ANKI_NOTE_TYPE: EA
  :ANKI_TAGS: ea_numbers
  :ANKI_NOTE_ID: 1624919231313
  :END:
** Front
How many bacteria are there?
** Back
Around \(5 \times 10^{30}\).
** Source
"There are approximately \(5 \times 10^{30}\) bacteria on Earth, forming a biomass which is only exceeded by plants." ([[https://en.wikipedia.org/wiki/Bacteria][Wikipedia]])
* Number of atoms in the affectable universe
  :PROPERTIES:
  :ANKI_DECK: EA-numbers
  :ANKI_NOTE_TYPE: EA
  :ANKI_TAGS: ea_numbers
  :ANKI_NOTE_ID: 1624919196463
  :END:
** Front
How many atoms are there in the affectable universe?
** Back
Between \(10^{78}\) and \(10^{82}\).
** Source
"it is estimated that the there are between \(10^{78}\) and \(10^{82}\) atoms in the known, observable universe." ([[https://www.universetoday.com/36302/atoms-in-the-universe/][Villanueva 2009]])
* Big tech market capitalization
  :PROPERTIES:
  :ANKI_DECK: EA-numbers
  :ANKI_NOTE_TYPE: EA
  :ANKI_TAGS: ea_numbers
  :ANKI_NOTE_ID: 1624919196540
  :END:
** Front
What is the market capitalization of the Big Five?
** Back
Around $8.5 trillion (June 2021).
** Source
[[https://companiesmarketcap.com/tech/largest-tech-companies-by-market-cap/][Companies Market Cap]]. The Big Five are Apple, Microsoft, Amazon, Google and Facebook. The largest Big Five company (Apple) is worth around $2 trillion, roughly twice as much as the smallest (Facebook).
* WHO budget
  :PROPERTIES:
  :ANKI_DECK: EA-numbers
  :ANKI_NOTE_TYPE: EA
  :ANKI_TAGS: ea_numbers
  :ANKI_NOTE_ID: 1624919196614
  :END:
** Front
What is the budget of the World Health Organization?
** Back
$4.5 billion (2021).
** Source
[[http://open.who.int/2020-21/budget-and-financing/summary][World Health Organization]]. Note that WHO reports budgets biennially, so the figure in their report is $9 billion.
* UN budget
  :PROPERTIES:
  :ANKI_DECK: EA-numbers
  :ANKI_NOTE_TYPE: EA
  :ANKI_TAGS: ea_numbers
  :ANKI_NOTE_ID: 1624919196696
  :END:
** Front
What is the budget of the United Nations?
** Back
$57 billion (2019).
** Source
[[https://unsceb.org/fs-revenue][United Nations]].
* BWC budget
  :PROPERTIES:
  :ANKI_DECK: EA-numbers
  :ANKI_NOTE_TYPE: EA
  :ANKI_TAGS: ea_numbers
  :ANKI_NOTE_ID: 1624919196801
  :END:
** Front
What is the budget of the Biological Weapons Convention?
** Back
$1.4 million (2019).
** Source
[[https://undocs.org/pdf?symbol=en/BWC/MSP/2019/5#:~:text=5.,been%20received%20from%20States%20Parties.][Report on the Overall Financial Situation of the Biological Weapons Convention]], p. 3, table 1. "Consider the possibility of engineered pandemics, which we shall soon see to be one of the largest risks facing humanity. The international body responsible for the continued prohibition of bioweapons (the Biological Weapons Convention) has an annual budget of just $1.4 million—less than the average McDonald’s restaurant." ([[https://theprecipice.com/][Ord 2020]]: 57)
* OPCW budget
  :PROPERTIES:
  :ANKI_DECK: EA-numbers
  :ANKI_NOTE_TYPE: EA
  :ANKI_TAGS: ea_numbers
  :ANKI_NOTE_ID: 1624919196879
  :END:
** Front
What is the budget of the Organisation for the Prohibition of Chemical Weapons?
** Back
€71 million (2020).
** Source
[[https://www.opcw.org/media-centre/opcw-numbers][OPCW]] ([[https://www.google.com/search?q=71+eur+to+usd][convert]] to USD).
* Japan's life expectancy at birth
  :PROPERTIES:
  :ANKI_DECK: EA-numbers
  :ANKI_NOTE_TYPE: EA
  :ANKI_TAGS: ea_numbers
  :ANKI_NOTE_ID: 1624919196972
  :END:
** Front
What is Japan's life expectancy at birth?
** Back
84.3 years (2020).
** Source
[[https://en.wikipedia.org/wiki/List_of_countries_by_life_expectancy][Wikipedia]]. Japan is the country with the highest life expectancy in the world (81.5 years for males and 86.9 years for females).
* Lesotho's life expectancy at birth
  :PROPERTIES:
  :ANKI_DECK: EA-numbers
  :ANKI_NOTE_TYPE: EA
  :ANKI_TAGS: ea_numbers
  :ANKI_NOTE_ID: 1624919197090
  :END:
** Front
What is Lesotho's life expectancy at birth?
** Back
50.7 years (2020).
** Source
[[https://en.wikipedia.org/wiki/List_of_countries_by_life_expectancy][Wikipedia]]. Lesotho is the country with the lowest life expectancy in the world (47.7 years for males and 54.2 years for females).
* World life expectancy at birth
  :PROPERTIES:
  :ANKI_DECK: EA-numbers
  :ANKI_NOTE_TYPE: EA
  :ANKI_TAGS: ea_numbers
  :ANKI_NOTE_ID: 1624919197394
  :END:
** Front
What is the world's life expectancy at birth?
** Back
73.3 years (2020).
** Source
[[https://en.wikipedia.org/wiki/List_of_countries_by_life_expectancy][Wikipedia]] (70.8 years for males and 75.9 years for females).
* World's life expectancy at birth in 1800
  :PROPERTIES:
  :ANKI_DECK: EA-numbers
  :ANKI_NOTE_TYPE: EA
  :ANKI_TAGS: ea_numbers
  :ANKI_NOTE_ID: 1624919197497
  :END:
** Front
What was the world's life expectancy at birth in 1800?
** Back
28.5 years.
** Source
[[https://ourworldindata.org/life-expectancy#rising-life-expectancy-around-the-world][Our World in Data]].
* Millionaires in the world
  :PROPERTIES:
  :ANKI_DECK: EA-numbers
  :ANKI_NOTE_TYPE: EA
  :ANKI_TAGS: ea_numbers
  :ANKI_NOTE_ID: 1624919197612
  :END:
** Front
How many millionaires are there in the world?
** Back
56 million (2021).

** Source
[[https://en.wikipedia.org/wiki/List_of_countries_by_the_number_of_millionaires][Wikipedia]]. About 40% of the world's millionaires are in the United States.
* Billionaires in the world
  :PROPERTIES:
  :ANKI_DECK: EA-numbers
  :ANKI_NOTE_TYPE: EA
  :ANKI_TAGS: ea_numbers
  :ANKI_NOTE_ID: 1624919197690
  :END:
** Front
How many billionaires are there in the world?
** Back
2,755 (March 2021).

** Source
[[https://en.wikipedia.org/wiki/List_of_countries_by_number_of_billionaires#cite_note-Forbes-1][Wikipedia]]. The United States and China have roughly the same number of billionaires, and they together account for about half of the world's billionaires.
* Computational power of the human brain
  :PROPERTIES:
  :ANKI_DECK: EA-numbers
  :ANKI_NOTE_TYPE: EA
  :ANKI_TAGS: ea_numbers
  :ANKI_NOTE_ID: 1624919197788
  :END:
** Front
How much computational power does it take to match the human brain?
** Back
Something like \(10^{15}\) floating point operations per second.
** Source
"Overall, I think it more likely than not that  \(10^{15}\) FLOP/s is enough to perform tasks as well as the human brain (given the right software, which may be very hard to create). And I think it unlikely (<10%) that more than \(10^{21}\) FLOP/s is required. But I’m not a neuroscientist, and there’s no consensus in neuroscience (or elsewhere)." ([[https://www.openphilanthropy.org/brain-computation-report][Carlsmith 2020]]; see the [[https://www.openphilanthropy.org/brain-computation-report#Appendix5][appendix]] for additional estimates)
* Pocket calculator share of total computation in 1986
  :PROPERTIES:
  :ANKI_DECK: EA-numbers
  :ANKI_NOTE_TYPE: EA
  :ANKI_TAGS: ea_numbers
  :ANKI_NOTE_ID: 1624919197868
  :END:
** Front
What share of total computation did pocket calculators account for in 1986?
** Back
41%.
** Source
"The calculator laid the cornerstone for modern microprocessors and was still the dominant way to compute information in 1986 (41% of \(3.0 \times 10^{8}\) general-purpose MIPS [million operations per second])." ([[https://doi.org/10.1126/science.1200970][Hilbert & López 2011]])
* Age of the oldest company
  :PROPERTIES:
  :ANKI_DECK: EA-numbers
  :ANKI_NOTE_TYPE: EA
  :ANKI_TAGS: ea_numbers
  :ANKI_NOTE_ID: 1624919198050
  :END:
** Front
How old is the oldest independent, continuously operating company in history?

** Back
1,428 years (578–2006).

** Source
[[https://en.wikipedia.org/wiki/List_of_oldest_companies][Wikipedia]]. The business is question is Kongō Gumi, a construction company founded in 578. In 2006, it became a subsidiary of the Takamatsu Construction Group.
* Primary energy consumption
  :PROPERTIES:
  :ANKI_DECK: EA-numbers
  :ANKI_NOTE_TYPE: EA
  :ANKI_TAGS: ea_numbers
  :ANKI_NOTE_ID: 1624919198165
  :END:
** Front
How much primary energy does the world consume in a year?
** Back
162,000 terawatt-hours.
** Source
[[https://ourworldindata.org/explorers/energy?tab=chart&country=~OWID_WRL&Total+or+Breakdown=Total&Energy+or+Electricity=Primary+energy&Metric=Annual+consumption][Our World in Data]].
* Cost to avert a death by supporting a top GiveWell charity
  :PROPERTIES:
  :ANKI_DECK: EA-numbers
  :ANKI_NOTE_TYPE: EA
  :ANKI_TAGS: ea_numbers
  :ANKI_NOTE_ID: 1624919198463
  :END:
** Front
What is the cost of averting a death by supporting a top GiveWell charity?
** Back
$3,000–$5,000.
** Source
"We estimate that $3,000 - $5,000 will save a life.﻿" ([[https://www.givewell.org/charities/top-charities][GiveWell]]) The charities for which this estimate is given are Malaria Consortium, Against Malaria Foundation, Helen Keller International and New Incentives. More precise figures may be found in their [[https://docs.google.com/spreadsheets/d/16XOOB1oWse1ICbF0OVXUYtwWwpvG3mxAAQ6LYAAndQU/edit#gid=1034883018&range=A29][cost-effectiveness model]].
* Cost to distribute a bed net
** Front
How much does it cost to provide a bed net for protection against malaria?
** Back
Around $5.
** Source
"We estimate that nets delivered by Against Malaria Foundation cost $4.95 each.﻿" ([[https://www.givewell.org/charities/top-charities/citations#Cost_of_providing_nets][GiveWell]])
* Number of chickens consumed annually in the US
  :PROPERTIES:
  :ANKI_DECK: EA-numbers
  :ANKI_NOTE_TYPE: EA
  :ANKI_TAGS: ea_numbers
  :ANKI_NOTE_ID: 1624919198538
  :END:
** Front
How many chickens does the average American eat every year?
** Back
23 (2013).

** Source
[[https://countinganimals.com/how-many-animals-does-a-vegetarian-save/][Sethu 2015]].
* Number of cows consumed per year in the US
  :PROPERTIES:
  :ANKI_DECK: EA-numbers
  :ANKI_NOTE_TYPE: EA
  :ANKI_TAGS: ea_numbers
  :ANKI_NOTE_ID: 1624919198688
  :END:
** Front
How many cows does the average American eat every year?
** Back
0.1 (2013).

** Source
[[https://countinganimals.com/how-many-animals-does-a-vegetarian-save/][Sethu 2015]].
* Chicken-years affected per dollar spent on campaigns
  :PROPERTIES:
  :ANKI_DECK: EA-numbers
  :ANKI_NOTE_TYPE: EA
  :ANKI_TAGS: ea_numbers
  :ANKI_NOTE_ID: 1624919198767
  :END:
** Front
How many chicken-years are affected per dollar spent on broiler and cage-free campaigns?
** Back
9–120.
** Source
"I estimate how many chickens will be affected by corporate cage-free and broiler welfare commitments won by all charities, in all countries, during all the years between 2005 and the end of 2018. According to my estimate, for every dollar spent, 9 to 120 years of chicken life will be affected. However, the estimate doesn't take into account indirect effects which could be more important." ([[https://forum.effectivealtruism.org/posts/L5EZjjXKdNgcm253H/corporate-campaigns-affect-9-to-120-years-of-chicken-life][Šimčikas 2019]]) See [[https://forum.effectivealtruism.org/posts/L5EZjjXKdNgcm253H/corporate-campaigns-affect-9-to-120-years-of-chicken-life#Ways_this_estimate_could_be_misleading][this section]] of that post for a list of ways in which the estimate may be misleading.
* Number of stars in the Milky Way
  :PROPERTIES:
  :ANKI_DECK: EA-numbers
  :ANKI_NOTE_TYPE: EA
  :ANKI_TAGS: ea_numbers
  :ANKI_NOTE_ID: 1624919198873
  :END:
** Front
How many stars does the Milky Way contain?
** Back
100–400 billion.
** Source
"[The Milky Way] is estimated to contain 100–400 billion stars and at least that number of planets." ([[https://en.wikipedia.org/wiki/Milky_Way][Wikipedia]])
* Number of galaxies in the affectable universe
  :PROPERTIES:
  :ANKI_DECK: EA-numbers
  :ANKI_NOTE_TYPE: EA
  :ANKI_TAGS: ea_numbers
  :ANKI_NOTE_ID: 1624919198947
  :END:
** Front
How many galaxies are there in the affectable universe?
** Back
Around 7 billion.
** Source
"The affectable universe contains about 7 billion galaxies with a total of between \(10^{21}\) and \(10^{23}\) stars." ([[https://arxiv.org/abs/2104.01191][Ord 2021]]: 22)
* Number of affectable galaxies lost per year
  :PROPERTIES:
  :ANKI_DECK: EA-numbers
  :ANKI_NOTE_TYPE: EA
  :ANKI_TAGS: ea_numbers
  :ANKI_NOTE_ID: 1624919199032
  :END:
** Front
How many affectable galaxies are lost every year?
** Back
Three.
** Source
"Each year the affectable universe will only shrink in volume by about one part in 5 billion. Even if we waited a million years, it would only diminish by one part in 5 thousand. It would take 50 million years, before its volume would shrink by 1%. In absolute terms, these would be losses on a scale beyond normal comprehension: the loss of 3 entire galaxies for every year of delay — thousands of stars every second. But for most purposes it is the relative scale that matters." ([[https://arxiv.org/abs/2104.01191][Ord 2021]]: 22)
* Fraction of world population killed by the Black Death
  :PROPERTIES:
  :ANKI_DECK: EA-numbers
  :ANKI_NOTE_TYPE: EA
  :ANKI_TAGS: ea_numbers
  :ANKI_NOTE_ID: 1624919199138
  :END:
** Front
What fraction of the world's population was killed by the Black Death?
** Back
Around 10%.
** Source
"By my estimate, the deadliest event before the industrial revolution (the Black Death) killed ~9.7% of world population, and the deadliest event after the industrial revolution (the 1918 flu pandemic) killed 3.3% of world population. [...] [M]y lowest plausible estimate adds up to 20,856,000, and my highest plausible estimate adds up to 68,016,000. The geometric mean of these two numbers is 37,666,533." ([[https://lukemuehlhauser.com/industrial-revolution/#DeadliestProcess][Muehlhauser 2017]])
* Fraction of world population killed by 1918 flu pandemic
  :PROPERTIES:
  :ANKI_DECK: EA-numbers
  :ANKI_NOTE_TYPE: EA
  :ANKI_TAGS: ea_numbers
  :ANKI_NOTE_ID: 1624919199215
  :END:
** Front
What fraction of the world's population was killed by the 1918 flu pandemic?
** Back
Around 3%.
** Source
"By my estimate, the deadliest event before the industrial revolution (the Black Death) killed ~9.7% of world population, and the deadliest event after the industrial revolution (the 1918 flu pandemic) killed 3.3% of world population. [...] To construct my estimate, I struck a balance between empirical estimates and speculation, relying more on the former than the latter, and (somewhat arbitrarily) guessed that the 1918 flu pandemic killed ~60 million people." ([[https://lukemuehlhauser.com/industrial-revolution/#DeadliestProcess][Muehlhauser 2017]])
* Fraction of world population killed in World War II
  :PROPERTIES:
  :ANKI_DECK: EA-numbers
  :ANKI_NOTE_TYPE: EA
  :ANKI_TAGS: ea_numbers
  :ANKI_NOTE_ID: 1624919199513
  :END:
** Front
What fraction of the world's population was killed in World War II?
** Back
Around 3%.
** Source
"Wikipedia’s List of wars and anthropogenic disasters by death toll provided “lowest” and “highest” estimates for World War II of 65 million and 85 million, respectively. However, I quickly found that in Matthew White’s collection of historians’ estimates of the death toll of World War II, /most/ estimates were lower than 55 million, with the median estimate at 50 million [about 2.9% of the world's population at the time]." ([[https://lukemuehlhauser.com/industrial-revolution/#DeadliestProcess][Muehlhauser 2017]])
* Fraction of psych studies that replicate
  :PROPERTIES:
  :ANKI_DECK: EA-numbers
  :ANKI_NOTE_TYPE: EA
  :ANKI_TAGS: ea_numbers
  :ANKI_NOTE_ID: 1624919199613
  :END:
** Front
What fraction of studies in psychology replicate?
** Back
35%–40%.
** Source
[[https://mfr.osf.io/render?url=https://osf.io/jq7v6/?action=download%26mode=render][Table 1]] of [[https://doi.org/10.1126/science.aac4716][Nosek 2015]] summarizes the main findings. Studies in cognitive psychology replicate at roughly twice the rate as studies in social psychology.
* Fraction of econ studies that replicate
  :PROPERTIES:
  :ANKI_DECK: EA-numbers
  :ANKI_NOTE_TYPE: EA
  :ANKI_TAGS: ea_numbers
  :ANKI_NOTE_ID: 1624919199689
  :END:
** Front
What fraction of studies in economics replicate?
** Back
Around 60%.
** Source
A /Science/ study found that about 60% of economics experiments successfully replicated ([[https://doi.org/10.1126%2Fscience.aaf0918][Camerer /et al/ 2016]]). Participants in the DARPA SCORE programme forecast that 58% of studies in economics will replicate ([[https://doi.org/10.1098/rsos.200566][Gordon /et al/ 2020]]).
* Fraction of history when humanity alive
  :PROPERTIES:
  :ANKI_DECK: EA-numbers
  :ANKI_NOTE_TYPE: EA
  :ANKI_TAGS: ea_numbers
  :ANKI_NOTE_ID: 1625155373261
  :END:
** Front
For what fraction of the history of the universe have humans been alive?
** Back
0.0022%.
** Source
As noted elsewhere in this deck, the universe has existed for 13.772 billion years and humanity has existed for 300,000 years. \( \frac{300,000}{13,722,000,000} = 0.00002186270223\).
